name: Deploy PostgreSQL with pgvector

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create docker-compose.yml
        run: |
          cat > docker-compose.yml << 'EOL'
          version: '3.8'

          services:
            postgres:
              image: ankane/pgvector
              container_name: postgres_db
              environment:
                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                POSTGRES_DB: postgres
              ports:
                - "5432:5432"
              volumes:
                - postgres_data:/var/lib/postgresql/data
              restart: unless-stopped

          volumes:
            postgres_data:
          EOL

      - name: Deploy PostgreSQL
        run: docker-compose up -d

      - name: Verify deployment
        run: |
          sleep 10
          docker ps
          docker-compose logs postgres

      - name: Setup Cloudflared tunnel
        run: |
          # Install cloudflared
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

          # Start tunnel (no auth needed for basic tunnels)
          cloudflared tunnel --url tcp://localhost:5432 > cloudflared.log 2>&1 &
          sleep 5

          # Extract and display URL
          grep -o 'https://.*\.trycloudflare.com' cloudflared.log | head -1

      - name: Keep alive
        run: sleep 300 # Keep runner alive for 5 minutes
