name: Deploy PostgreSQL with pgvector to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create fly.toml
        run: |
          cat > fly.toml << 'EOL'
          app = "amazing-postgres"

          [build]
          image = "ankane/pgvector"

          [env]
          POSTGRES_USER = "postgres"
          POSTGRES_PASSWORD = "postgres" # You should use secrets for this
          POSTGRES_DB = "postgres"

          [mounts]
          source = "postgres_data"
          destination = "/var/lib/postgresql/data"

          [http_service]
            internal_port = 5432
            force_https = true
            auto_stop_machines = false
            auto_start_machines = true
          EOL

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Output connection information
        run: |
          echo "PostgreSQL deployed to Fly.io"
          echo "Connection string: postgres://postgres:postgres@amazing-postgres.fly.dev:5432/postgres"
